server:
  port: 8094
  servlet.context-path: /admin
  servlet.session.timeout: 600M
  
logging:
 level:
  net.mingsoft: trace
ms:
 manager: 
  path: /ms
  view-path: /WEB-INF/manager
  
 upload: 
   path: /upload
   #windows
   #distPath: d:/sdbj_cms/ms_mcms/upload
   #linux
   distPath: /opt/data/mcms/upload
   denied: exe
   allowed: jpg,exe,mp4
   max-size: 1
   memory-size: 4096
      
spring:
  http.multipart.enabled: false
  profiles:
    active: prod
  mvc:
    pathmatch:
      use-suffix-pattern: true
    static-path-pattern: /upload/**
  resources: 
  #windows
    #static-locations: file:d://sdbj_cms//ms_mcms//upload
  #linux
    static-locations: file:/opt/data/mcms/upload
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**
  servlet:
    multipart:
      max-request-size: 500MB
      enabled: false
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    allow-request-override: true
    allow-session-override: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: false
    template-loader-path: classpath:/WEB-INF/manager,classpath:/WEB-INF
    settings: 
      template_update_delay: 1
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      auto_import: /include/macro.ftl as ms
      
mybatis:
  mapper-locations: classpath*:**/dao/*.xml,**/mapper/*.xml
  configuration: 
   database-id: sqlServer
   
#时间戳统一转换

#swagger开关
swagger:
   enable: true

