#spring:
#  datasource:
#    url: jdbc:mysql://47.106.217.46:3306/db_mcms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
#    username: db_mcms
#    password: TSkMPHF4aLfHiHGw
#    filters: wall,mergeStat
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=50000
    initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
    maxPoolPreparedStatementPerConnectionSize: 20
    base:
      #url: jdbc:mysql://47.106.217.46:3306/db_mcms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      #username: db_mcms
      #password: TSkMPHF4aLfHiHGw
      #type: com.alibaba.druid.pool.DruidDataSource
      #driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:sqlserver://10.60.230.195:20175;DatabaseName=mcms
      username: sa
      password: U2RiakBTZXJ2ZXIyMDE5XzE5NV9IUg==
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    zentao:
      url: jdbc:sqlserver://10.60.230.195:20175;DatabaseName=ykchr
      username: sa
      password: U2RiakBTZXJ2ZXIyMDE5XzE5NV9IUg==
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

############quartz
quartz:
  properties: /quartz-prod.properties

####webService
project:
  webService:
    url: http://kk.baju.com.cn:8094/slsd8j/services/projectinfoService?wsdl
    getProjectList: getProjectList
    getAreaList: getAreaList

